n_graphs: 10             # Number of graphs
try_before_stop: 20      # Stop after generating try_before_stop points unsucessfully in a row
n_max: 100              # max number of points in the graph
save: True
save_path: './data/synthetic'

# 1st constraint: atoms must be inside a bounding box
min_bound: [0.0, 0.0, 0.0]
max_bound: [1.0, 2.0, 4.0]

# 2nd constraint: atoms should not be too close from each other
use_constraint2: True
min_dist: 0.3

# Third constraint: not too many atoms should be close
use_constraint3: True
num_neighbors_max: 3
neighbor_threshold: 0.8